/*=============================================================================
 * icon - a BAKED icon descriptor, the shared type every icons_<name>.h
 * generated by tools/gen_icons.py instantiates a table of.
 *
 * Mirrors gfx_font_t (gfx_font.h): the hand-written struct lives here, once,
 * so more than one generated atlas (gfx/icons_system.h today, an app's own
 * apps/<name>/icons_<name>.h later - see docs/plans/Icon-Baker-Plan.md's
 * "Ownership") can each define a `static const icon_t` table without
 * redeclaring the type.
 *
 * `offset` INTO A SHARED rows[] BLOB, NOT A POINTER
 *
 * Every generated table stores its icon's row bytes as one plain integer
 * offset into that same header's `rows[]` array, not `const uint8_t *rows`.
 * A pointer member would still be `const`, but it is not a plain value - the
 * runtime has to fix it up against wherever the blob actually loaded before
 * the table is usable, the same class of relocation cost `gfx_font_t.atlas`
 * accepts because a font is looked up through one hand-written accessor per
 * role (gfx_font_roles.h) rather than a whole table of them. An offset needs
 * none of that: the table is pure data, exactly as `static const` promises.
 *
 * WHY A RUNTIME TABLE IS FINE HERE, UNLIKE A FONT ROLE
 *
 * gfx_font_roles.h argues hard against ever resolving a font through a
 * runtime-indexed table: an 8bpp coverage atlas is hundreds of KiB, so a
 * registry naming every candidate from one translation unit would force all
 * of them to link, undoing the linker's ability to drop an unselected one.
 * A 16x16 1bpp icon is 32 bytes; a hundred of them is a few KiB - the
 * calculus a font role is built around does not apply, so an icon table
 * indexed by a generated enum is the plain, ordinary way to look one up.
 *===========================================================================*/
#pragma once

#include <stdint.h>

typedef struct {
    uint16_t offset;   /* byte offset into that header's rows[] blob */
    uint8_t  w, h;
    uint8_t  stride;   /* bytes per row: (w + 7) / 8, MSB is column 0 */
    uint8_t  blocks;   /* baked run-length rect count - see gen_icons.py */
} icon_t;
