/*=============================================================================
 * boot_anim - the startup animation: the zeta function spiralling up its own
 * critical line.
 *
 * This header is the MATHS and the CHOREOGRAPHY - the projection, the
 * smoothing, the colour and the timeline. boot_anim.c is the drawing and the
 * five seconds of frame loop, and boot_anim_curve.h is the curve itself,
 * generated by tools/gen_zeta_curve.py. The split is the one gfx_color.h,
 * icons.h and ui_style.h already make: everything here is integer arithmetic
 * with no BSP, no driver and no framebuffer in sight, so
 * test/suites/suite_boot_anim.c can check all of it on a laptop. Nobody can
 * eyeball a fixed-point projection and tell you whether it is the right one.
 *
 * WHAT IS BEING DRAWN
 *
 * Three axes. Two of them are the complex plane that zeta's VALUE lives in -
 * the real part running down and to the right, the imaginary part down and to
 * the left at 45 degrees - and they are drawn as a floor, with a grid on it.
 * The third is t, straight up, which is the HEIGHT UP THE CRITICAL LINE the
 * function is being evaluated at.
 *
 * The curve is then zeta(1/2 + it) for t from 0 to 35, plotted at height t.
 * It winds round the vertical axis because the value keeps circling the
 * origin, and the loops grow as t does. Where it actually touches the t axis
 * the value is zero - and those five points are the first five nontrivial
 * zeros of the zeta function, marked as the pen passes them.
 *
 * So the picture is not decorative arithmetic: the Riemann hypothesis is the
 * conjecture that this line is the only place those crossings happen.
 *
 * FIXED POINT, AND THREE SCALES OF IT
 *
 * The chip has no FPU, so everything is integers. Mixing the scales up is the
 * mistake to watch for:
 *
 *   Q12   a value of zeta. 4096 is 1.0, one unit of the floor grid.
 *   Q8    a height t. 256 is 1.0, and 35 * 256 still fits an int16.
 *   Q8    the projection's own axis vectors, in pixels per unit.
 *===========================================================================*/
#pragma once

#include <stdint.h>

#include "boot/boot_anim_curve.h"

#define BOOT_ANIM_Q    12
#define BOOT_ANIM_ONE  (1 << BOOT_ANIM_Q)   /* 4096 == 1.0 */
#define BOOT_ANIM_TQ   8                    /* t's own fixed point */

/*---------------------------------------------------------------------------
 * The projection
 *
 * An axonometric one: three fixed directions on screen, no perspective and no
 * matrix. Perspective would cost a divide per point and buy nothing - there
 * is no camera to move and nothing hidden behind anything else.
 *
 * Screen size arrives as a parameter rather than as GFX_WIDTH/GFX_HEIGHT,
 * because gfx.h drags in the BSP and this file has to compile on a host.
 * gfx_dirty.h has the same problem and mirrors the two numbers as literals;
 * taking them as arguments leaves nothing to drift out of step.
 *-------------------------------------------------------------------------*/

#define BOOT_ANIM_Z_PX  35     /* pixels per unit of zeta's value */
#define BOOT_ANIM_T_PX   9     /* pixels per unit of t            */
#define BOOT_ANIM_T_MAX 35     /* the top of the climb            */

/* The floor grid has no edge: its lines run until they leave the panel, and
 * what bounds it is a fade rather than a boundary.
 *
 * A grid drawn to a fixed square reads as a square tile floating in the dark,
 * which is a thing sitting in the scene. A grid that thins out with distance
 * reads as a plane carrying on past the screen, which is what a coordinate
 * plane actually is. gfx_line() clips, so rings that fall off the edge cost
 * nothing to ask for.
 *
 * RINGS is therefore how far the fade reaches rather than how big the floor
 * is: ring FADE is fully dark, so nothing past it is worth drawing at all. */
#define BOOT_ANIM_GRID_RINGS 7
#define BOOT_ANIM_GRID_FADE  7

/* Where one unit along each axis lands, in Q8 pixels.
 *
 *   real       20 degrees below horizontal, to the right
 *   imaginary  45 degrees below horizontal, to the left
 *
 * 45 for the imaginary axis because that is the angle that reads as "going
 * away from you". 20 rather than another 45 for the real one because two
 * symmetric axes make a floor that looks like it is being seen edge on, with
 * the grid squares collapsed into slivers.
 *
 * Q8 rather than Q12 for headroom: these multiply a Q12 value of up to about
 * 3.7, and at Q12 that product would come within a factor of two of
 * overflowing an int32. That failure would show up as the curve folding in
 * half at its widest point - not as anything that announces itself.
 */
#define BOOT_ANIM_RE_X  8420   /*  cos(20) * Z_PX * 256           */
#define BOOT_ANIM_RE_Y  3064   /*  sin(20) * Z_PX * 256, downward */
#define BOOT_ANIM_IM_X (-6336) /* -cos(45) * Z_PX * 256           */
#define BOOT_ANIM_IM_Y  6336   /*  sin(45) * Z_PX * 256, downward */

/* The origin - where t is 0 and zeta is 0 - sits low and centred, because
 * everything else is above it. */
static inline int boot_anim_origin_x(int w) { return w / 2; }
static inline int boot_anim_origin_y(int h) { return (h * 3) / 4; }

/* (value, height) -> pixel.
 *
 * The shift is 20 because a Q12 value times a Q8 pixels-per-unit is Q20. t is
 * already Q8, so its own term only sheds 8.
 *
 * NOT util/fixed.h, deliberately, and this is the reason the axis vectors are
 * Q8 rather than Q12 in the first place. fx_mul_floor() exists to make the
 * widening cast unforgettable at sites that need one; these do not need one,
 * because the operands were sized so the product cannot overflow an int32 -
 * the largest is about 1.7e8 against a 2.1e9 ceiling. Routing them through a
 * 64-bit helper would put back the arithmetic the scale choice exists to
 * avoid, on a path that runs several thousand times a frame.
 *
 * Both terms are also summed BEFORE the shift, which fx_mul_floor() cannot
 * express: flooring each product separately and then adding can land a pixel
 * off the one the geometry asks for. */
static inline int boot_anim_screen_x(int w, int32_t re_q12, int32_t im_q12)
{
    return boot_anim_origin_x(w) +
           (int)((re_q12 * BOOT_ANIM_RE_X + im_q12 * BOOT_ANIM_IM_X) >> 20);
}

static inline int boot_anim_screen_y(int h, int32_t re_q12, int32_t im_q12,
                                     int32_t t_q8)
{
    return boot_anim_origin_y(h) +
           (int)((re_q12 * BOOT_ANIM_RE_Y + im_q12 * BOOT_ANIM_IM_Y) >> 20) -
           (int)((t_q8 * BOOT_ANIM_T_PX) >> BOOT_ANIM_TQ);
}

/*---------------------------------------------------------------------------
 * Smoothing
 *
 * 205 samples of a curve that crosses most of the screen is a chord every six
 * pixels or so, and at that size a polyline reads as a polyline - the tight
 * turns near the axis visibly have corners. Rather than carry more samples,
 * the ones there are get drawn as a spline.
 *-------------------------------------------------------------------------*/

/* Straight segments per span. Four puts a joint every pixel and a half at the
 * curve's tightest, which is well under what anyone can see. */
#define BOOT_ANIM_SPLINE_STEPS 4

typedef struct {
    int32_t re, im;   /* Q12 */
    int32_t t;        /* Q8  */
} boot_anim_pt_t;

/* A point on the uniform quadratic B-spline through c0, c1, c2, at `t_q12`
 * from 0 - which lands on the midpoint of c0 and c1 - to BOOT_ANIM_ONE, the
 * midpoint of c1 and c2. Consecutive spans therefore meet, and the result is
 * one continuous curve.
 *
 * WHY A B-SPLINE AND NOT A CATMULL-ROM
 *
 * The obvious choice for "smooth curve through my points" interpolates them,
 * and Catmull-Rom overshoots wherever they turn sharply. Here that is exactly
 * the interesting part of the picture - the curve whipping round the axis at
 * a zero - and an overshoot would put a bulge precisely where the whole point
 * is that the curve passes through a particular place.
 *
 * A B-spline stays inside the convex hull of its control points instead,
 * because its weights are non-negative and sum to a constant. It does not
 * pass through them - it cuts the corners - and that IS the smoothing: the
 * samples are a sampling of a smooth function, so the corners are an artifact
 * of the sampling rather than a feature of the curve.
 *
 * Quadratic rather than cubic for one practical reason: a quadratic's weights
 * sum to 2, so normalising is a shift. A cubic's sum to 6, and a divide per
 * coordinate per sub-step is thousands of divides a frame on the slowest
 * integer instruction this chip has.
 */
static inline boot_anim_pt_t boot_anim_spline(boot_anim_pt_t c0,
                                              boot_anim_pt_t c1,
                                              boot_anim_pt_t c2,
                                              int32_t t_q12)
{
    /* 32-bit throughout, for the same reason boot_anim_screen_x() is - see
     * its comment on why util/fixed.h is not used here. t_q12 is at most
     * BOOT_ANIM_ONE, so the weights are at most 2.0 in Q12 and the three
     * weighted samples sum to well under 4e7. */
    const int32_t u  = BOOT_ANIM_ONE - t_q12;
    const int32_t w0 = (u * u) >> BOOT_ANIM_Q;
    const int32_t w2 = (t_q12 * t_q12) >> BOOT_ANIM_Q;

    /* The three weights sum to 2.0 by construction, so the middle one is
     * never computed from its own polynomial - and so cannot drift from the
     * other two if it is not. */
    const int32_t w1 = 2 * BOOT_ANIM_ONE - w0 - w2;

    boot_anim_pt_t p;
    p.re = (w0 * c0.re + w1 * c1.re + w2 * c2.re) >> (BOOT_ANIM_Q + 1);
    p.im = (w0 * c0.im + w1 * c1.im + w2 * c2.im) >> (BOOT_ANIM_Q + 1);
    p.t  = (w0 * c0.t  + w1 * c1.t  + w2 * c2.t ) >> (BOOT_ANIM_Q + 1);
    return p;
}

/* Sample `i` of the generated curve, clamped at both ends.
 *
 * Clamping rather than wrapping or refusing is what pins the spline to the
 * ends of the curve: a repeated first control point makes the first span
 * start exactly at the first sample instead of half a span along it. */
static inline boot_anim_pt_t boot_anim_sample(int i)
{
    if (i < 0) {
        i = 0;
    } else if (i >= BOOT_ANIM_CURVE_POINTS) {
        i = BOOT_ANIM_CURVE_POINTS - 1;
    }
    boot_anim_pt_t p;
    p.re = boot_anim_curve[i].re;
    p.im = boot_anim_curve[i].im;
    p.t  = boot_anim_curve[i].t;
    return p;
}

/*---------------------------------------------------------------------------
 * The choreography
 *
 * Every phase is a function of milliseconds since power-up rather than of a
 * frame counter, so the animation lasts five seconds whatever the frame rate
 * turns out to be - and it does move, because a frame costs a full-screen
 * transfer plus however much curve there is to draw by then.
 *-------------------------------------------------------------------------*/

#define BOOT_ANIM_MS 3000

#define BOOT_ANIM_AXES_MS        450   /* the axes grow out of the origin */

#define BOOT_ANIM_GRID_START_MS  150
#define BOOT_ANIM_GRID_RING_MS    45   /* each ring waits for the one inside */
#define BOOT_ANIM_GRID_FADE_MS   300

#define BOOT_ANIM_PEN_START_MS   520
#define BOOT_ANIM_PEN_MS        1980

#define BOOT_ANIM_FADE_START_MS 2650   /* dissolve into the launcher */

/* 0 before `start_ms`, 255 from `start_ms + dur_ms` on, linear between. */
static inline uint8_t boot_anim_ramp(uint32_t now_ms, uint32_t start_ms,
                                     uint32_t dur_ms)
{
    if (now_ms <= start_ms) {
        return 0;
    }
    const uint32_t elapsed = now_ms - start_ms;
    if (dur_ms == 0 || elapsed >= dur_ms) {
        return 255;
    }
    return (uint8_t)((elapsed * 255u) / dur_ms);
}

/* Fast off the mark, settling as it arrives. Motion that starts and stops at
 * the same speed reads as mechanical; one squared term is enough to stop it
 * looking like a progress bar. */
static inline uint8_t boot_anim_ease_out(uint8_t linear)
{
    const uint32_t left = 255u - linear;
    return (uint8_t)(255u - (left * left) / 255u);
}

/* How far along each axis the pen has reached, 0..255 of the way to its far
 * end. A FRACTION, not a pixel count: the three arms are three different
 * lengths on screen and still have to arrive together. */
static inline uint8_t boot_anim_axis_reach(uint32_t now_ms)
{
    return boot_anim_ease_out(boot_anim_ramp(now_ms, 0, BOOT_ANIM_AXES_MS));
}

/* Floor grid lines fade in from the origin outward - `ring` is 1 for the
 * first line either side of an axis, 2 for the next, and so on - and fade
 * OUT again with distance, which is what gives the floor no edge.
 *
 * The two fades multiply. The first is the animation arriving; the second is
 * the plane receding, and it is what the eye reads as depth on a projection
 * that has no perspective in it at all. */
/* The brightest the floor is ever allowed to get.
 *
 * Low, and the number that mattered most here. The floor is backdrop: it says
 * where the plane is and then gets out of the way. Drawn at anything like
 * full strength it competes with the curve for attention and wins, because
 * there is a great deal more of it - which is exactly what the first version
 * of this did, and the curve disappeared into a plaid tablecloth. */
#define BOOT_ANIM_GRID_MAX 56

static inline uint8_t boot_anim_grid_alpha(uint32_t now_ms, int ring)
{
    if (ring >= BOOT_ANIM_GRID_FADE) {
        return 0;
    }
    const uint32_t start = BOOT_ANIM_GRID_START_MS +
                           (uint32_t)ring * BOOT_ANIM_GRID_RING_MS;
    const uint32_t arrived = boot_anim_ramp(now_ms, start,
                                            BOOT_ANIM_GRID_FADE_MS);

    /* Squared, not linear: a linear falloff still has visible lines most of
     * the way out and then stops, which puts an edge back on the floor in a
     * different place. Squared, the outer rings are already almost gone by
     * the time they run out. */
    const uint32_t left = (uint32_t)(BOOT_ANIM_GRID_FADE - ring);
    const uint32_t near = left * left * BOOT_ANIM_GRID_MAX /
                          ((uint32_t)BOOT_ANIM_GRID_FADE * BOOT_ANIM_GRID_FADE);

    return (uint8_t)((arrived * near) / 255u);
}

_Static_assert(BOOT_ANIM_PEN_START_MS + BOOT_ANIM_PEN_MS <=
               BOOT_ANIM_FADE_START_MS,
               "the curve must be finished before the picture starts fading");

/*---------------------------------------------------------------------------
 * Colour
 *
 * The panel is an AMOLED: an unlit pixel is genuinely off, not a backlight
 * leaking through black, so saturated colour on a true black field is the one
 * thing this screen does that an LCD cannot. Hence a hue wheel rather than a
 * house colour - the curve turns most of the way round it on the way up, so
 * height reads as colour and the whole climb is one gradient.
 *
 * Only the HUE is computed here. Brightness and desaturation come out as
 * amounts to mix toward the background and toward white, and the mixing is
 * gfx_color_mix() in gfx_color.h - already written, already tested, and
 * already aware that the panel's green channel has a bit more range than the
 * other two.
 *-------------------------------------------------------------------------*/

/* A whole turn: six sectors of 256, so the sector is a shift and the ramp
 * within one is a byte. */
#define BOOT_ANIM_HUE_TURN 1536

/* 0xRRGGBB at full saturation and full brightness. */
static inline uint32_t boot_anim_hue_rgb(int hue)
{
    hue %= BOOT_ANIM_HUE_TURN;
    if (hue < 0) {
        hue += BOOT_ANIM_HUE_TURN;
    }

    const uint32_t ramp = (uint32_t)(hue & 0xFF);   /* rising edge, 0..255 */
    const uint32_t fall = 255u - ramp;

    switch (hue >> 8) {
    case 0:  return (0xFFu << 16) | (ramp << 8);            /* red     -> yellow  */
    case 1:  return (fall << 16) | (0xFFu << 8);            /* yellow  -> green   */
    case 2:  return (0xFFu << 8) | ramp;                    /* green   -> cyan    */
    case 3:  return (fall << 8) | 0xFFu;                    /* cyan    -> blue    */
    case 4:  return (ramp << 16) | 0xFFu;                   /* blue    -> magenta */
    default: return (0xFFu << 16) | fall;                   /* magenta -> red     */
    }
}

/* The grid's own colour, as a hue wheel position, drifting with time and
 * with distance from the origin.
 *
 * The floor is the one thing on screen that is up the whole time and does
 * nothing, so it is where a slow colour change costs nothing and is not in
 * competition with anything. Distance is folded in as well as time, so the
 * rings do not all change together - the colour travels outward as a wave
 * instead of the whole floor blinking. */
#define BOOT_ANIM_GRID_HUE_MS     2600   /* one whole turn takes this long */
#define BOOT_ANIM_GRID_HUE_SPREAD 70     /* wheel positions per ring outward */

static inline int boot_anim_grid_hue(uint32_t now_ms, int ring)
{
    const uint32_t turn = (now_ms % BOOT_ANIM_GRID_HUE_MS) *
                          BOOT_ANIM_HUE_TURN / BOOT_ANIM_GRID_HUE_MS;
    return (int)turn + ring * BOOT_ANIM_GRID_HUE_SPREAD;
}

/* How much of the curve has been drawn, as a Q12 fraction of its length.
 *
 * A fraction of LENGTH, not of t: the samples are spaced at a constant
 * distance ON SCREEN (see tools/gen_zeta_curve.py), so walking them at a
 * constant rate moves the pen at a constant speed. Pacing by t instead would
 * crawl round the wide loops and race up the straight stretches between
 * them. */
static inline int32_t boot_anim_pen(uint32_t now_ms)
{
    const uint8_t linear = boot_anim_ramp(now_ms, BOOT_ANIM_PEN_START_MS,
                                          BOOT_ANIM_PEN_MS);
    return ((int32_t)linear * BOOT_ANIM_ONE) / 255;
}

/* Everything drawn is mixed up from the background by this, so the last
 * stretch dissolves the whole picture rather than cutting from a lit screen
 * straight to the menu. */
static inline uint8_t boot_anim_ink(uint32_t now_ms)
{
    return (uint8_t)(255u - boot_anim_ramp(now_ms, BOOT_ANIM_FADE_START_MS,
                                           BOOT_ANIM_MS - BOOT_ANIM_FADE_START_MS));
}

#define BOOT_ANIM_HUE_START 875    /* azure, at the foot of the climb */
#define BOOT_ANIM_HUE_SWEEP 1200   /* most of a turn by the top       */

/* SEVERAL PENS, NOT ONE
 *
 * One pen puts one colour on the curve at a time, and this panel can show
 * rather more than that. Five of them run the same curve at a fixed spacing,
 * each carrying its own fifth of the wheel, so at any moment most of the
 * gamut is on screen at once and the curve reads as being washed by colour
 * rather than drawn in it.
 *
 * The leading pen is still the one that reveals the curve; the rest travel
 * over ground already covered. */
#define BOOT_ANIM_TRAILS    5

/* How far apart the pens run, as a Q12 fraction of the whole curve. */
#define BOOT_ANIM_TRAIL_GAP 768

/* How far behind a pen its own trail still glows. A quarter of the curve
 * each: long enough to fade out slowly rather than read as a spark being
 * dragged along, short enough that five of them stay five bands instead of
 * merging into one uniform glow.
 *
 * A power of two so the falloff below is a shift rather than a divide, of
 * which there would otherwise be tens of thousands a frame. */
#define BOOT_ANIM_TRAIL_SHIFT 10
#define BOOT_ANIM_TRAIL_Q12   (1 << BOOT_ANIM_TRAIL_SHIFT)

/* Strokes at least this lit are drawn this many pixels across instead of
 * one, so the live parts of the curve are visibly heavier than the settled
 * ones. */
#define BOOT_ANIM_FAT_TRAIL 150
#define BOOT_ANIM_FAT_WIDTH 3

/* Where pen `k` is, as a Q12 fraction of the curve. Negative until it has set
 * off, which is what staggers their starts without a second clock. */
static inline int32_t boot_anim_trail_pos(int32_t pen_q12, int k)
{
    return pen_q12 - (int32_t)k * BOOT_ANIM_TRAIL_GAP;
}

/* The wheel position pen `k` carries, spread evenly round it. */
static inline int boot_anim_trail_hue(int k)
{
    return k * (BOOT_ANIM_HUE_TURN / BOOT_ANIM_TRAILS);
}

typedef struct {
    int     hue;     /* wheel position; boot_anim_hue_rgb() wraps it */
    uint8_t bloom;   /* mix that far toward white                    */
    uint8_t glow;    /* mix that far up from the background          */
    uint8_t width;   /* pixels across                                */
} boot_anim_stroke_t;

/* How one piece of the curve is coloured: `along_q12` is where that piece
 * sits along the curve, `pen_q12` is where the LEADING pen has got to.
 *
 * Two things are added. A BASE, which depends only on position and is what
 * the finished picture looks like once the pens have stopped; and whichever
 * PEN is closest in front of this piece, which is what makes the drawing look
 * like drawing.
 *
 * The strongest pen wins outright rather than the five being summed. Summing
 * saturates wherever two trails overlap - and they overlap constantly - so
 * the bands smear into one bright stretch and their colours average out
 * toward white, which is the opposite of the point.
 *
 * Its hue is mixed in BY STRENGTH rather than switched to, so a piece of
 * curve halfway between two pens comes out halfway between their colours
 * instead of snapping from one to the other as the lead changes.
 *
 * Each trail falls off linearly rather than as a square. A squared falloff
 * piles the glow up right behind the head and is over almost at once, and a
 * trail that fades out slowly is the entire point of having one. */
static inline boot_anim_stroke_t boot_anim_stroke(int32_t along_q12,
                                                  int32_t pen_q12)
{
    boot_anim_stroke_t s;

    const int32_t base_glow  = 132 + ((along_q12 * 60) >> BOOT_ANIM_Q);
    const int32_t base_bloom = (along_q12 * 24) >> BOOT_ANIM_Q;
    const int base_hue = BOOT_ANIM_HUE_START +
                         (int)((along_q12 * BOOT_ANIM_HUE_SWEEP) >> BOOT_ANIM_Q);

    int32_t best = 0;
    int     best_hue = 0;

    for (int k = 0; k < BOOT_ANIM_TRAILS; k++) {
        const int32_t behind = boot_anim_trail_pos(pen_q12, k) - along_q12;
        if (behind < 0 || behind >= BOOT_ANIM_TRAIL_Q12) {
            continue;   /* this piece is ahead of that pen, or long past it */
        }
        const int32_t trail = 255 - ((behind * 255) >> BOOT_ANIM_TRAIL_SHIFT);
        if (trail > best) {
            best = trail;
            best_hue = boot_anim_trail_hue(k);
        }
    }

    /* (best + 1) >> 8, not best / 255: a shift is a divide's worth of cycles
     * cheaper and there are tens of thousands of these a frame, and the +1 is
     * what makes the shift land exactly on the endpoints - without it a
     * full-strength trail comes out one short of full brightness. */
    s.hue   = base_hue + ((best_hue * (best + 1)) >> 8);
    s.glow  = (uint8_t)(base_glow  + (((255 - base_glow) * (best + 1)) >> 8));
    s.bloom = (uint8_t)(base_bloom + (((90 - base_bloom) * (best + 1)) >> 8));
    s.width = best >= BOOT_ANIM_FAT_TRAIL ? BOOT_ANIM_FAT_WIDTH : 1;

    return s;
}

/*---------------------------------------------------------------------------
 * The one hardware-facing entry point
 *
 * Declared here and defined in boot_anim.c, the same arrangement icon_check()
 * has at the bottom of icons.h: a declaration costs this header none of its
 * host-portability, and a second header for one function would be worse.
 *-------------------------------------------------------------------------*/

/* Draw the whole animation, start to finish - about BOOT_ANIM_MS of it.
 *
 * BLOCKS, and is meant to: it runs during boot, before the shell's frame loop
 * exists and before there is anything to switch to. gfx_init() must have
 * succeeded first. Yields every frame so the watchdog stays fed. */
void boot_anim_run(void);
