/*=============================================================================
 * gen_wave_table - print the baked water_wave[256] table material.c ships,
 * computed from its own documented formula instead of hand-typed.
 *
 * Run through report_wave_table.sh, which builds this, captures its stdout,
 * and either writes it out for pasting into material.c or (--check) diffs it
 * against the table already there - see that script's own top comment for
 * why it exists as a separate step from the safety net below.
 *
 * WHY A GENERATOR AND NOT 256 HAND-TYPED NUMBERS
 *
 * material.c's own top comment on water_wave[] is the single source of the
 * formula - three sine components, given frequency/amplitude/phase, summed,
 * normalised, and scaled to WAVE_AMP. Anyone re-deriving the table by hand
 * from that prose, twice (once to bake it, once to check it), is exactly how
 * a baked table and the formula it claims to follow drift apart without
 * either side ever noticing. This file is that derivation, done once, in
 * code, so the numbers in material.c are reproducible from the formula
 * rather than trusted by inspection.
 *
 * THE REAL SAFETY NET IS THE TEST, NOT THIS FILE
 *
 * test_the_wave_table_matches_its_formula (suite_sand.c) recomputes the same
 * formula independently, in a host test, and asserts it matches material.c's
 * baked table entry for entry - that is what runs on every `run_tests.sh` and
 * is what actually catches drift. This generator exists so the table can be
 * PRODUCED without hand-typing it in the first place; it is not itself part
 * of the test suite and nothing depends on it being run.
 *
 * Deliberately NOT linked against material.c the way dump_reactions.c (this
 * folder's other generator) is. dump_reactions.c has to link and read real
 * struct tables full of constant expressions (MATX(), SAND_SHOCK_HEAT, ...);
 * this table is 256 numbers derived from six literal constants (three
 * frequencies, three amplitudes, three phases) that are simplest just
 * written down here, in the same form the test writes them down in. */

#include <math.h>
#include <stdint.h>
#include <stdio.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* Mirrors material.c's own WAVE_FRAC_BITS/WAVE_AMP - see that file's comment
 * on water_wave[] for what the fixed-point scale is for. Kept as plain
 * literals here rather than a shared header: this program and material.c
 * agree by both being read against the SAME prose, not by sharing a
 * #define, and a generator with no other reason to include material.h
 * gains one only to borrow two integers from it. */
#define WAVE_FRAC_BITS 4
#define WAVE_AMP       40   /* 40 / 16 = 2.5 shade steps, in Q4 */

/* The formula, exactly as material.c documents it: three sine components,
 * frequencies 2/5/9 cycles over the 256-entry table, relative amplitudes
 * 1.0/0.6/0.35, phase offsets 0.0/2.1/4.0 radians - summed, normalised by
 * the sum of the absolute amplitudes (so the sum can never exceed +-1 by
 * the triangle inequality, whatever the phases do), then scaled to
 * WAVE_AMP and rounded to the nearest integer (ties away from zero, the
 * ordinary meaning of round()). test_the_wave_table_matches_its_formula
 * re-states this same arithmetic independently - see its own comment for
 * why bit-identical reproduction across two independently-written
 * implementations is the property that matters here, not just "close". */
static int8_t wave_entry(int i)
{
    static const double freq[3]  = { 2.0, 5.0, 9.0 };
    static const double amp[3]   = { 1.0, 0.6, 0.35 };
    static const double phase[3] = { 0.0, 2.1, 4.0 };
    const double amp_sum = amp[0] + amp[1] + amp[2];

    double v = 0.0;
    for (int k = 0; k < 3; k++) {
        v += amp[k] * sin(2.0 * M_PI * freq[k] * (double)i / 256.0 + phase[k]);
    }

    const double scaled = (v / amp_sum) * (double)WAVE_AMP;
    return (int8_t)lround(scaled);
}

int main(void)
{
    printf("/* GENERATED by launcher/main/apps/sand/tools/gen_wave_table.c "
           "via\n");
    printf(" * launcher/main/apps/sand/tools/report_wave_table.sh - do not "
           "edit by hand.\n");
    printf(" * Edit the formula there (and in this file's own comment "
           "above), and\n");
    printf(" * regenerate; test_the_wave_table_matches_its_formula "
           "(suite_sand.c) is\n");
    printf(" * what actually keeps this honest on every test run. */\n");
    printf("static const int8_t water_wave[256] = {\n");

    for (int row = 0; row < 256; row += 16) {
        printf("   ");
        for (int col = 0; col < 16; col++) {
            printf(" %4d,", wave_entry(row + col));
        }
        printf("\n");
    }

    printf("};\n");
    return 0;
}
